### ISSUE TITLE
pcd8544_fb.py Suggestion to make compatible with Writer class.

### ISSUE THREAD

**Issue by peterhinch** [mcauser/micropython-pcd8544#2]
If you add to the constructor the lines
```python
		self.height = HEIGHT  # For Writer class
		self.width = WIDTH
```
this driver becomes compatible with my [Writer class](https://github.com/peterhinch/micropython-font-to-py.git). This enables arbitrary fonts  created by font_to_py.py to be rendered in normal or inverse text, centre or right justified, plus other features.

**Comment by mcauser** [comment]
Added in https://github.com/mcauser/micropython-pcd8544/commit/791d4239d77b0d06192c7ab7903d81a72a53f992
