### ISSUE TITLE
bitmap converter

### ISSUE THREAD

**Issue by mdinata** [mcauser/micropython-pcd8544#3]
hi, what converter do you use (online/offline) to convert image to byterray? Thanks

**Comment by Kyuchumimo** [comment]
Hi, I have a python script that serves that purpose: : https://github.com/Kyuchumimo/84x48-Bitmap-to-ByteArray

![E0-lWOVXEAEMmzg](https://user-images.githubusercontent.com/74131798/139572579-6280870d-9ca1-4320-873e-2d9d56f28bf6.png)
![IMG_20210509_230250](https://user-images.githubusercontent.com/74131798/139572605-bc82fff8-53b6-4774-8be6-68ae31661a46.jpg)

**Comment by mdinata** [comment]
That is great, thanks for sharing. I will try it.
