### ISSUE TITLE
How to write text?

### ISSUE THREAD

**Issue by HoleForYou** [mcauser/micropython-pcd8544#5]
How do I write text to the display? Do I just have to use the bitmap for everything? 

Is there anything for displaying simple text?

**Comment by mcauser** [comment]
Hi, the display does not have any built in fonts.
One way to write text to the display is to use the [framebuf](https://docs.micropython.org/en/latest/library/framebuf.html).

If you take a look at framebuf in the /examples folder, it shows you how you can draw text to the framebuf buffer (bytearray), then write the entire buffer to the display:
https://github.com/mcauser/micropython-pcd8544/blob/master/examples/framebuf.py#L23

If you want to use a different font, or do not wish to fill the entire display with a single framebuf buffer, you can make a bunch of smaller buffers containing individual characters or glyphs, then write them as needed, eg:
https://github.com/mcauser/micropython-pcd8544/blob/master/examples/screen_saver.py#L19
